export const sampleExercises = [
  {
    title: 'Dynamic Warm-Up Circuit',
    description: 'A comprehensive warm-up routine to prepare players physically and mentally for training',
    category: 'warm-up' as const,
    difficulty: 'beginner' as const,
    duration: 15,
    videoUrl: 'https://www.youtube.com/watch?v=example1',
    equipment: ['Cones', 'Markers'],
    objectives: ['Increase heart rate', 'Improve flexibility', 'Activate muscle groups'],
    instructions: 'Players move through stations performing high knees, butt kicks, lateral shuffles, and dynamic stretches. Each exercise lasts 30 seconds with 15 seconds rest between.',
    variations: 'Add resistance bands for advanced players or reduce intensity for younger age groups',
    coachingPoints: ['Focus on proper form', 'Gradual intensity increase', 'Monitor player fatigue'],
    ageGroup: 'U12-U18',
    playerCount: '10-20',
    spaceRequired: '20x20 meters'
  },
  {
    title: 'Passing Triangle Drill',
    description: 'Develop passing accuracy and first touch in a triangle formation',
    category: 'technical' as const,
    difficulty: 'beginner' as const,
    duration: 20,
    videoUrl: 'https://www.youtube.com/watch?v=example2',
    equipment: ['Balls', 'Cones'],
    objectives: ['Improve passing accuracy', 'Enhance first touch', 'Build communication'],
    instructions: 'Three players form a triangle 10 meters apart. Pass clockwise, then counter-clockwise. Receiver must control with first touch and pass with second touch.',
    variations: 'Add one-touch passing, increase distance, add defensive pressure',
    coachingPoints: ['Weight of pass', 'Body shape when receiving', 'Communication before receiving'],
    ageGroup: 'U10-U16',
    playerCount: '3-15 (groups of 3)',
    spaceRequired: '15x15 meters per group'
  },
  {
    title: 'Rondo 4v2',
    description: 'Possession game to improve passing under pressure and defensive positioning',
    category: 'technical' as const,
    difficulty: 'intermediate' as const,
    duration: 25,
    videoUrl: 'https://www.youtube.com/watch?v=example3',
    equipment: ['Balls', 'Cones'],
    objectives: ['Maintain possession', 'Quick decision making', 'Defensive pressing'],
    instructions: 'Four players on the outside keep possession while two defenders try to win the ball. If defenders win or ball goes out, they swap with the player who lost it.',
    variations: 'Limit touches (2-touch or 1-touch), change grid size, add neutral player',
    coachingPoints: ['Create passing angles', 'Quick ball movement', 'Defensive communication'],
    ageGroup: 'U14-Adult',
    playerCount: '6-18 (multiple grids)',
    spaceRequired: '10x10 meters per grid'
  },
  {
    title: 'Small-Sided Game 5v5',
    description: 'Tactical game focusing on team shape and transition play',
    category: 'tactical' as const,
    difficulty: 'intermediate' as const,
    duration: 30,
    videoUrl: 'https://www.youtube.com/watch?v=example4',
    equipment: ['Balls', 'Goals', 'Bibs'],
    objectives: ['Apply tactical concepts', 'Improve decision making', 'Enhance fitness'],
    instructions: '5v5 on a 40x30 meter pitch with small goals. Focus on maintaining shape in possession and quick transition when losing the ball.',
    variations: 'Add conditions (2-touch max, must pass to all players before scoring)',
    coachingPoints: ['Team shape', 'Support play', 'Transition speed'],
    ageGroup: 'U12-Adult',
    playerCount: '10-20',
    spaceRequired: '40x30 meters'
  },
  {
    title: 'Shooting from Distance',
    description: 'Practice shooting technique and power from outside the box',
    category: 'technical' as const,
    difficulty: 'intermediate' as const,
    duration: 20,
    videoUrl: 'https://www.youtube.com/watch?v=example5',
    equipment: ['Balls', 'Goal', 'Cones'],
    objectives: ['Improve shooting technique', 'Increase shot power', 'Accuracy from distance'],
    instructions: 'Players take turns shooting from 20-25 meters. Focus on proper technique: plant foot beside ball, strike through center, follow through.',
    variations: 'Add a defender, shoot after dribbling, volleys and half-volleys',
    coachingPoints: ['Body over the ball', 'Strike through center', 'Follow through towards target'],
    ageGroup: 'U14-Adult',
    playerCount: '6-15',
    spaceRequired: 'Half pitch'
  },
  {
    title: 'Speed and Agility Ladder',
    description: 'Improve footwork, coordination, and agility using ladder drills',
    category: 'physical' as const,
    difficulty: 'beginner' as const,
    duration: 15,
    videoUrl: 'https://www.youtube.com/watch?v=example6',
    equipment: ['Agility ladder', 'Cones'],
    objectives: ['Enhance footwork', 'Improve coordination', 'Increase agility'],
    instructions: 'Players perform various footwork patterns through the ladder: in-in-out-out, lateral shuffles, hopscotch, icky shuffle. 3 sets of each pattern.',
    variations: 'Add ball control after ladder, increase speed, combine patterns',
    coachingPoints: ['Quick feet', 'Stay on toes', 'Maintain balance'],
    ageGroup: 'U10-Adult',
    playerCount: '10-20',
    spaceRequired: '10x5 meters'
  },
  {
    title: 'Defensive 1v1 Positioning',
    description: 'Teach defenders proper positioning and timing in 1v1 situations',
    category: 'tactical' as const,
    difficulty: 'intermediate' as const,
    duration: 20,
    videoUrl: 'https://www.youtube.com/watch?v=example7',
    equipment: ['Balls', 'Cones', 'Small goals'],
    objectives: ['Improve defensive positioning', 'Learn when to engage', 'Practice recovery runs'],
    instructions: 'Attacker starts with ball 20 meters from goal. Defender must delay, show attacker to weaker side, and prevent shot or pass.',
    variations: 'Add second attacker, change starting positions, add time pressure',
    coachingPoints: ['Defensive stance', 'Patience', 'Force to weaker side'],
    ageGroup: 'U12-Adult',
    playerCount: '8-16 (pairs)',
    spaceRequired: '20x15 meters per pair'
  },
  {
    title: 'Crossing and Finishing',
    description: 'Practice wide play, crossing technique, and finishing in the box',
    category: 'technical' as const,
    difficulty: 'advanced' as const,
    duration: 25,
    videoUrl: 'https://www.youtube.com/watch?v=example8',
    equipment: ['Balls', 'Goal', 'Cones'],
    objectives: ['Improve crossing accuracy', 'Enhance finishing', 'Timing of runs'],
    instructions: 'Winger receives ball wide and delivers cross. Attackers make runs to near post, far post, and edge of box. Rotate positions after each cross.',
    variations: 'Add defenders, vary cross types (low, high, cut-back), time restrictions',
    coachingPoints: ['Cross quality', 'Run timing', 'Finishing technique'],
    ageGroup: 'U14-Adult',
    playerCount: '8-15',
    spaceRequired: 'Penalty area + wings'
  },
  {
    title: 'High-Intensity Interval Training',
    description: 'Build endurance and explosive power through interval training',
    category: 'physical' as const,
    difficulty: 'advanced' as const,
    duration: 20,
    videoUrl: 'https://www.youtube.com/watch?v=example9',
    equipment: ['Cones', 'Stopwatch'],
    objectives: ['Increase cardiovascular fitness', 'Build explosive power', 'Improve recovery'],
    instructions: '30 seconds maximum effort sprint, 30 seconds active recovery (jog). Repeat 10-12 times. Focus on maintaining intensity throughout.',
    variations: 'Change work/rest ratios, add ball work, include direction changes',
    coachingPoints: ['Maximum effort during work periods', 'Active recovery', 'Proper breathing'],
    ageGroup: 'U16-Adult',
    playerCount: '10-25',
    spaceRequired: '50 meters straight line'
  },
  {
    title: 'Static Stretching Cool-Down',
    description: 'Proper cool-down routine to aid recovery and prevent injury',
    category: 'cool-down' as const,
    difficulty: 'beginner' as const,
    duration: 10,
    videoUrl: 'https://www.youtube.com/watch?v=example10',
    equipment: [],
    objectives: ['Aid muscle recovery', 'Improve flexibility', 'Prevent injury'],
    instructions: 'Hold each stretch for 30 seconds: hamstrings, quadriceps, calves, hip flexors, groin, shoulders. Focus on breathing and gradual stretch.',
    variations: 'Partner-assisted stretching, foam rolling, yoga poses',
    coachingPoints: ['No bouncing', 'Breathe deeply', 'Gradual stretch'],
    ageGroup: 'U10-Adult',
    playerCount: 'Any',
    spaceRequired: 'Minimal'
  }
];
