import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.features": "Features",
    "nav.gallery": "Gallery",
    "nav.team": "Our Team",
    "nav.events": "Events",
    "nav.pricing": "Pricing",
    "nav.reviews": "Reviews",
    "nav.contact": "Contact",
    "nav.dashboard": "Go to Dashboard",
    "nav.register": "Register Now",
    "nav.login": "Login",
    "nav.academyTeams": "Academy Teams",
    "nav.rewards": "Rewards",
    
    // Hero Section
    "hero.badge": "Egypt's Premier Youth Football Academy",
    "hero.title1": "Develop",
    "hero.title2": "Future",
    "hero.title3": "Football",
    "hero.title4": "Stars",
    "hero.description": "A technology-driven academy combining elite coaching, sports science, mental wellness, and nutrition to develop complete athletes.",
    "hero.cta.register": "Register Now",
    "hero.cta.dashboard": "Enter Dashboard",
    "hero.video.title": "Live Training Session",
    "hero.video.subtitle": "Future Stars FC Academy",
    
    // Stats
    "stats.players": "Active Players",
    "stats.coaches": "Professional Coaches",
    "stats.satisfaction": "Parent Satisfaction",
    "stats.graduates": "Pro Graduates",
    
    // Features Section
    "features.title": "Complete Player Development",
    "features.subtitle": "Our holistic approach covers every aspect of football development",
    "features.coaching.title": "Elite Coaching",
    "features.coaching.desc": "UEFA-licensed coaches with professional playing experience",
    "features.analytics.title": "Performance Analytics",
    "features.analytics.desc": "Data-driven insights to track and optimize player development",
    "features.mental.title": "Mental Wellness",
    "features.mental.desc": "Sports psychology support for confidence and resilience",
    "features.nutrition.title": "Nutrition Plans",
    "features.nutrition.desc": "Personalized meal plans for optimal athletic performance",
    "features.video.title": "Video Analysis",
    "features.video.desc": "Match and training footage review for tactical improvement",
    "features.tracking.title": "Progress Tracking",
    "features.tracking.desc": "Comprehensive reports on skill development and growth",
    
    // Gallery Section
    "gallery.title": "Training Gallery",
    "gallery.subtitle": "See our players in action during training sessions and matches",
    
    // Team Section
    "team.title": "Meet Our Coaching Staff",
    "team.subtitle": "Experienced professionals dedicated to developing the next generation",
    "team.viewAll": "View All Coaches",
    
    // Reviews Section
    "reviews.title": "What Parents Say",
    "reviews.subtitle": "Hear from families who have experienced the Future Stars FC difference",
    
    // FAQ Section
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Find answers to common questions about our academy",
    
    // Location Section
    "location.title": "Our Location",
    "location.subtitle": "Visit us at The Square Compound, New Cairo",
    "location.address": "The Square Compound, 5th Settlement, New Cairo, Egypt",
    
    // Footer
    "footer.description": "Developing the next generation of football stars through elite coaching, sports science, and holistic player development.",
    "footer.quickLinks": "Quick Links",
    "footer.programs": "Programs",
    "footer.contact": "Contact Us",
    "footer.rights": "All rights reserved.",
    
    // Common
    "common.learnMore": "Learn More",
    "common.viewMore": "View More",
    "common.backToHome": "Back to Home",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.welcome": "Welcome",
    
    // Pricing Page
    "pricing.title": "Membership Plans",
    "pricing.subtitle": "Choose the perfect plan for your child's football journey",
    "pricing.monthly": "Monthly",
    "pricing.quarterly": "3 Months",
    "pricing.semiannual": "6 Months",
    "pricing.annual": "Annual",
    "pricing.perMonth": "/month",
    "pricing.save": "Save",
    "pricing.popular": "Most Popular",
    "pricing.bestValue": "Best Value",
    "pricing.includes": "What's Included",
    "pricing.excludes": "Note: Prices exclude football kits and special events",
    "pricing.getStarted": "Get Started",
    
    // Events Page
    "events.title": "Upcoming Events",
    "events.subtitle": "Join our training sessions, tournaments, and special events",
    "events.register": "Register",
    "events.spotsLeft": "spots left",
    "events.full": "Full",
    
    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "We'd love to hear from you",
    "contact.form.name": "Your Name",
    "contact.form.email": "Email Address",
    "contact.form.phone": "Phone Number",
    "contact.form.message": "Your Message",
    "contact.form.send": "Send Message",
    
    // Player Dashboard
    "player.profile": "Player Profile",
    "player.skills": "Skills",
    "player.activities": "Activities",
    "player.targets": "Targets",
    "player.trends": "Trends",
    "player.explore": "Explore",
    "player.attendance": "Attendance",
    "player.points": "Points",
    "player.rewards": "Rewards",
    
    // Dashboard Menu
    "menu.videoAnalysis": "Video Analysis",
    "menu.videoClipLibrary": "Video Clip Library",
    "menu.tacticalHub": "Tactical Hub",
    "menu.aiEmergencyMode": "AI Emergency Mode",
    "menu.matchReports": "Match Reports",
    "menu.opponentAnalysis": "Opponent Analysis",
    "menu.xgAnalytics": "xG Analytics",
    "menu.analytics": "Analytics",
    "menu.gpsTracker": "GPS Tracker",
    "menu.matchManagement": "Match Management",
    "menu.recordMatchEvents": "Record Match Events",
    "menu.leagueFixtures": "League & Fixtures",
    "menu.footballLaws": "Football Laws",
    "menu.coachingCourses": "Coaching Courses",
    "menu.trainingVideos": "Training Videos",
    "menu.coachAssessment": "Coach Assessment",
    "menu.coachDashboard": "Coach Dashboard",
    
    // Tactical Hub
    "tacticalHub.title": "Tactical Hub",
    "tacticalHub.subtitle": "Complete tactical planning and analysis platform for coaches",
    "tacticalHub.attackSequence": "Attack Sequence",
    "tacticalHub.attackSequenceDesc": "Plan attacking movements",
    "tacticalHub.tacticalSimulation": "Tactical Simulation",
    "tacticalHub.tacticalSimulationDesc": "Test formations & strategies",
    "tacticalHub.matchReview": "3D Match Review",
    "tacticalHub.matchReviewDesc": "Analyze past matches",
    "tacticalHub.setPieces": "Set Pieces",
    "tacticalHub.setPiecesDesc": "Corner & free kick plans",
    "tacticalHub.aiPlanner": "AI Tactical Planner",
    "tacticalHub.aiPlannerDesc": "AI-powered tactical recommendations",
    "tacticalHub.loadOpponent": "Load Opponent Analysis",
    "tacticalHub.setPiecePlan": "Set Piece Plan",
    "tacticalHub.shortCornerPlay": "Short Corner Play",
    "tacticalHub.shortCornerDesc": "Short pass to create better angle",
    "tacticalHub.typeCornerShort": "Type: CORNER SHORT",
    "tacticalHub.players": "Players",
    "tacticalHub.playAnimation": "Play Animation",
    "tacticalHub.savePlan": "Save Plan",
    "tacticalHub.createCustom": "Create Custom",
    
    // Coach Certification Assessment
    "coachCert.title": "Coach Certification Assessment",
    "coachCert.subtitle": "Test your knowledge and earn FIFA coaching licenses",
    "coachCert.grassroots": "Grassroots Coaching Certificate",
    "coachCert.grassrootsDesc": "Entry-level coaching for youth development (Ages 4-12)",
    "coachCert.grassrootsBadge": "GRASSROOTS",
    "coachCert.uefaC": "UEFA/FIFA C License",
    "coachCert.uefaCDesc": "Foundation level for coaching youth teams",
    "coachCert.uefaCBadge": "C LICENSE",
    "coachCert.uefaB": "UEFA/FIFA B License",
    "coachCert.uefaBDesc": "Advanced coaching for semi-professional levels",
    "coachCert.uefaBBadge": "B LICENSE",
    "coachCert.uefaA": "UEFA/FIFA A License",
    "coachCert.uefaADesc": "Professional-level coaching qualification",
    "coachCert.uefaABadge": "A LICENSE",
    "coachCert.uefaPro": "UEFA Pro / FIFA Pro License",
    "coachCert.uefaProDesc": "Highest coaching qualification for top-tier clubs",
    "coachCert.uefaProBadge": "PRO LICENSE",
    "coachCert.duration": "Duration",
    "coachCert.questions": "Questions",
    "coachCert.passingScore": "Passing Score",
    "coachCert.startAssessment": "Start Assessment",
    "coachCert.minutes": "minutes",
    "coachCert.questionsCount": "questions",
    "coachCert.results": "Results",
    "coachCert.score": "Score",
    "coachCert.passed": "Passed!",
    "coachCert.failed": "Failed",
    "coachCert.tryAgain": "Try Again",
    "coachCert.viewCertificate": "View Certificate",
    "coachCert.congratulations": "Congratulations!",
    "coachCert.passedMessage": "You have passed the assessment",
    "coachCert.failedMessage": "You did not achieve the required passing score",
    "coachCert.yourScore": "Your Score",
    "coachCert.requiredScore": "Required Score",
    "coachCert.pass": "Pass",
    "coachCert.next": "Next",
    "coachCert.previous": "Previous",
    "coachCert.submit": "Submit Quiz",
    "coachCert.backToCourses": "Back to Courses",
    "coachCert.question": "Question",
    "coachCert.of": "of",
    "coachCert.selectAnswer": "Select your answer",
    "coachCert.progress": "Progress",
    "coachCert.timeRemaining": "Time Remaining",
    "coachCert.incompleteQuiz": "Incomplete Quiz",
    "coachCert.answerAllQuestions": "Please answer all questions before submitting.",
    "coachCert.quizSubmitted": "Quiz submitted successfully!",
    "coachCert.submissionError": "Failed to submit quiz. Please try again.",
    "coachCert.correct": "Correct",
    "coachCert.incorrect": "Incorrect",
    "coachCert.total": "Total",
    "coachCert.certificateEarned": "Certificate Earned!",
    "coachCert.congratsComplete": "Congratulations on completing the course!",
    "coachCert.tryAnotherCourse": "Try Another Course",
    "coachCert.answered": "answered",
    "coachCert.complete": "Complete",
    "coachCert.submitting": "Submitting...",
    
    // Training Sessions
    "training.title": "Training Sessions",
    "training.subtitle": "Manage and schedule training sessions for your teams",
    "training.scheduleSession": "Schedule Session",
    "training.createSession": "Schedule Training Session",
    "training.createDescription": "Create a new training session for a team",
    "training.editSession": "Edit Training Session",
    "training.sessionCreated": "Training session created successfully",
    "training.sessionUpdated": "Training session updated successfully",
    "training.sessionDeleted": "Training session deleted",
    "training.sessionFailed": "Failed to create session",
    "training.confirmDelete": "Are you sure you want to delete this session?",
    "training.noSessions": "No training sessions scheduled",
    "training.upcomingSessions": "Upcoming Sessions",
    "training.pastSessions": "Past Sessions",
    "training.todaySessions": "Today's Sessions",
    
    // Training Form Fields
    "training.sessionTitle": "Session Title",
    "training.team": "Team",
    "training.selectTeam": "Select team",
    "training.date": "Date",
    "training.startTime": "Start Time",
    "training.endTime": "End Time",
    "training.duration": "Duration",
    "training.location": "Location",
    "training.sessionType": "Session Type",
    "training.intensity": "Intensity",
    "training.objectives": "Objectives",
    "training.drills": "Drills",
    "training.description": "Description",
    "training.notes": "Notes",
    "training.equipment": "Equipment Needed",
    "training.attendance": "Attendance",
    "training.present": "Present",
    "training.absent": "Absent",
    "training.late": "Late",
    
    // Session Types
    "training.type.technical": "Technical",
    "training.type.tactical": "Tactical",
    "training.type.physical": "Physical",
    "training.type.mental": "Mental",
    "training.type.matchPrep": "Match Preparation",
    "training.type.recovery": "Recovery",
    "training.type.mixed": "Mixed",
    
    // Intensity Levels
    "training.intensity.low": "Low",
    "training.intensity.medium": "Medium",
    "training.intensity.high": "High",
    
    // Session Status
    "training.status.scheduled": "Scheduled",
    "training.status.inProgress": "In Progress",
    "training.status.completed": "Completed",
    "training.status.cancelled": "Cancelled",
    
    // Actions
    "training.viewDetails": "View Details",
    "training.cancelSession": "Cancel Session",
    "training.markComplete": "Mark Complete",
    "training.takeAttendance": "Take Attendance",
    "training.addDrill": "Add Drill",
    "training.saveDraft": "Save as Draft",
    "training.publish": "Publish Session",
    
    // Performance Tracking
    "performance.title": "Performance Tracking",
    "performance.subtitle": "Monitor and analyze player performance metrics",
    "performance.overview": "Performance Overview",
    "performance.technicalScore": "Technical Score",
    "performance.physicalScore": "Physical Score",
    "performance.tacticalScore": "Tactical Score",
    "performance.mentalScore": "Mental Score",
    "performance.overallScore": "Overall Score",
    "performance.recentMetrics": "Recent Metrics",
    "performance.trends": "Performance Trends",
    "performance.comparison": "Peer Comparison",
    "performance.strengths": "Strengths",
    "performance.weaknesses": "Areas for Improvement",
    "performance.recommendations": "Recommendations",
    
    // Physical Metrics
    "physical.title": "Physical Training",
    "physical.subtitle": "Manage physical conditioning and workouts",
    "physical.distance": "Distance Covered",
    "physical.sprints": "Sprints",
    "physical.topSpeed": "Top Speed",
    "physical.workload": "Training Load",
    "physical.fatigue": "Fatigue Level",
    "physical.recovery": "Recovery Status",
    "physical.injury": "Injury Status",
    "physical.workout": "Workout Plan",
    "physical.strength": "Strength Training",
    "physical.endurance": "Endurance",
    "physical.speed": "Speed Work",
    "physical.agility": "Agility",
    "physical.flexibility": "Flexibility",
    
    // Mental Coaching
    "mental.title": "Mental Coaching",
    "mental.subtitle": "Support psychological development and resilience",
    "mental.assessment": "Mental Assessment",
    "mental.anxiety": "Anxiety Level",
    "mental.confidence": "Confidence",
    "mental.focus": "Focus",
    "mental.resilience": "Resilience",
    "mental.stress": "Stress Level",
    "mental.motivation": "Motivation",
    "mental.wellbeing": "Overall Wellbeing",
    "mental.session": "Coaching Session",
    "mental.techniques": "Mental Techniques",
    "mental.progress": "Progress Tracking",
    
    // Nutrition
    "nutrition.title": "Nutrition Planning",
    "nutrition.subtitle": "Optimize performance through proper nutrition",
    "nutrition.mealPlan": "Meal Plan",
    "nutrition.calories": "Calories",
    "nutrition.protein": "Protein",
    "nutrition.carbs": "Carbohydrates",
    "nutrition.fats": "Fats",
    "nutrition.hydration": "Hydration",
    "nutrition.supplements": "Supplements",
    "nutrition.preTraining": "Pre-Training Meal",
    "nutrition.postTraining": "Post-Training Meal",
    "nutrition.matchDay": "Match Day Nutrition",
    "nutrition.recommendations": "Nutritional Recommendations",
    
    // Events (additional keys)
    "events.upcoming": "Upcoming Events",
    "events.past": "Past Events",
    "events.registered": "Registered",
    "events.date": "Event Date",
    "events.location": "Location",
    "events.ageGroup": "Age Group",
    "events.capacity": "Capacity",
    "events.cost": "Cost",
    "events.free": "Free",
    "events.details": "Event Details",
    "events.registrationSuccess": "Successfully registered for event",
    "events.registrationFailed": "Registration failed",
    
    // Match Management
    "match.title": "Match Management",
    "match.subtitle": "Track matches, results, and player statistics",
    "match.upcoming": "Upcoming Matches",
    "match.results": "Match Results",
    "match.schedule": "Match Schedule",
    "match.opponent": "Opponent",
    "match.venue": "Venue",
    "match.home": "Home",
    "match.away": "Away",
    "match.kickoff": "Kick-off Time",
    "match.result": "Result",
    "match.score": "Score",
    "match.win": "Win",
    "match.loss": "Loss",
    "match.draw": "Draw",
    "match.goals": "Goals",
    "match.assists": "Assists",
    "match.lineup": "Lineup",
    "match.substitutions": "Substitutions",
    "match.statistics": "Match Statistics",
    "match.report": "Match Report",
    
    // Video Analysis
    "video.title": "Video Analysis",
    "video.subtitle": "Analyze match and training footage",
    "video.upload": "Upload Video",
    "video.library": "Video Library",
    "video.recent": "Recent Videos",
    "video.match": "Match Video",
    "video.training": "Training Video",
    "video.analysis": "Analysis",
    "video.tags": "Tags",
    "video.notes": "Notes",
    "video.share": "Share",
    "video.download": "Download",
    
    // Analytics
    "analytics.title": "Analytics Dashboard",
    "analytics.subtitle": "Data-driven insights and performance analysis",
    "analytics.overview": "Overview",
    "analytics.team": "Team Analytics",
    "analytics.player": "Player Analytics",
    "analytics.comparison": "Comparison",
    "analytics.trends": "Trends",
    "analytics.reports": "Reports",
    "analytics.export": "Export Data",
    
    // GPS Tracker
    "gps.title": "GPS Tracking",
    "gps.subtitle": "Monitor player movement and workload",
    "gps.distance": "Distance",
    "gps.speed": "Speed",
    "gps.acceleration": "Acceleration",
    "gps.heartRate": "Heart Rate",
    "gps.zones": "Intensity Zones",
    "gps.heatmap": "Movement Heatmap",
    "gps.session": "Session Data",
    "gps.sync": "Sync Data",
    
    // Live Match Mode
    "liveMatchMode": "Live Match Mode",
    "liveMatchModeDescription": "Track and manage your match in real-time with AI tactical assistance",
    "startNewMatch": "Start New Match",
    "matchStarted": "Match Started",
    "liveMatchModeActivated": "Live match mode activated successfully",
    "selectTeam": "Select Team",
    "opponent": "Opponent",
    "opponentName": "Opponent Name",
    "venue": "Venue",
    "home": "Home",
    "away": "Away",
    "ourFormation": "Our Formation",
    "opponentFormation": "Opponent Formation",
    "optional": "Optional",
    "selectFormation": "Select Formation",
    "starting": "Starting...",
    "startMatch": "Start Match",
    "matchTime": "Match Time",
    "start": "Start",
    "pause": "Pause",
    "resume": "Resume",
    "finish": "Finish",
    "score": "Score",
    "us": "Us",
    "formation": "Formation",
    "changeTactics": "Change Tactics",
    "quickActions": "Quick Actions",
    "goal": "Goal",
    "yellowCard": "Yellow Card",
    "redCard": "Red Card",
    "substitution": "Substitution",
    "injury": "Injury",
    "penalty": "Penalty",
    "substitutionsUsed": "Substitutions Used",
    "yellowCards": "Yellow Cards",
    "redCards": "Red Cards",
    "liveStatistics": "Live Statistics",
    "possession": "Possession",
    "shots": "Shots",
    "onTarget": "on target",
    "opponentShots": "Opponent Shots",
    "corners": "Corners",
    "fouls": "Fouls",
    "aiTacticalAssistant": "AI Tactical Assistant",
    "analyzing": "Analyzing...",
    "getAIAdvice": "Get AI Advice",
    "clickToGetAIAdvice": "Click the button above to get AI tactical recommendations",
    "matchEvents": "Match Events",
    "assist": "Assist",
    "noEventsYet": "No events recorded yet",
    "tacticalChanges": "Tactical Changes",
    "recordEvent": "Record Event",
    "eventType": "Event Type",
    "team": "Team",
    "playerName": "Player Name",
    "enterPlayerName": "Enter player name",
    "assistBy": "Assist By",
    "enterAssistPlayerName": "Enter assist player name",
    "playerOut": "Player Out",
    "notes": "Notes",
    "additionalNotes": "Additional notes",
    "recording": "Recording...",
    "eventRecorded": "Event Recorded",
    "matchEventSaved": "Match event saved successfully",
    "changeType": "Change Type",
    "tacticalInstruction": "Tactical Instruction",
    "playerRole": "Player Role",
    "pressingIntensity": "Pressing Intensity",
    "defensiveLine": "Defensive Line",
    "newFormation": "New Formation",
    "newValue": "New Value",
    "enterNewValue": "Enter new value",
    "reason": "Reason",
    "whyThisChange": "Why this change?",
    "saving": "Saving...",
    "saveTacticalChange": "Save Tactical Change",
    "tacticsChanged": "Tactics Changed",
    "tacticalChangeSaved": "Tactical change saved successfully",
    "matchFinished": "Match Finished",
    "matchDataSaved": "Match data saved successfully",
    "confirmFinishMatch": "Are you sure you want to finish this match?",
    "fillAllFields": "Please fill all required fields",
    "ownGoal": "Own Goal",
    "varDecision": "VAR Decision",
    "loading": "Loading...",
    "error": "Error",
    
    // Heatmap & GPS
    "playerHeatmap": "Player Heatmap",
    "refresh": "Refresh",
    "download": "Download",
    "selectPlayer": "Select Player",
    "showAllPlayers": "Show All Players",
    "selectPlayerToViewHeatmap": "Select a player to view their heatmap",
    "lowToHighIntensity": "Low to High Intensity",
    "autoRefreshEvery30Seconds": "Auto-refresh every 30 seconds",
    "gpsIntegration": "GPS Integration",
    "gpsIntegrationDescription": "Import GPS tracking data or sync live during the match",
    "liveGpsSync": "Live GPS Sync",
    "deviceId": "Device ID",
    "startGpsSync": "Start GPS Sync",
    "activeSyncs": "Active Syncs",
    "dataPoints": "data points",
    "importGpsFile": "Import GPS File",
    "importGpsFileDescription": "Upload a CSV file with GPS tracking data",
    "importing": "Importing...",
    "clickToUploadCsv": "Click to upload CSV file",
    "dataPointsImported": "data points imported successfully",
    "importFailed": "Import failed",
    "instructions": "Instructions",
    "gpsInstruction1": "Start live sync to track player positions in real-time during the match",
    "gpsInstruction2": "Or import a CSV file with historical GPS data (format: playerId, minute, x, y, speed, heartRate)",
    "gpsInstruction3": "Heatmap will automatically update every 30 seconds during live matches",
    "gpsSyncStarted": "GPS Sync Started",
    "gpsSyncStartedSuccess": "GPS sync started successfully for selected player",
    "failedToStartGpsSync": "Failed to start GPS sync",
    "gpsDataImported": "GPS Data Imported",
    "failedToImportGpsData": "Failed to import GPS data",
    "gpsSync": "GPS Sync",
  },
  ar: {
    // Navigation
    "nav.features": "المميزات",
    "nav.gallery": "معرض الصور",
    "nav.team": "المدربون",
    "nav.events": "الفعاليات",
    "nav.pricing": "الباقات",
    "nav.reviews": "آراء أولياء الأمور",
    "nav.contact": "تواصل معنا",
    "nav.dashboard": "لوحة التحكم",
    "nav.register": "سجّل الآن",
    "nav.login": "دخول",
    "nav.academyTeams": "فرق الأكاديمية",
    "nav.rewards": "المكافآت",
    
    // Hero Section
    "hero.badge": "الأكاديمية الرائدة لكرة القدم للناشئين في مصر",
    "hero.title1": "نُنمّي",
    "hero.title2": "نجوم",
    "hero.title3": "كرة القدم",
    "hero.title4": "المستقبل",
    "hero.description": "أكاديمية متطورة تجمع بين التدريب المتميز وعلوم الرياضة والدعم النفسي والتغذية السليمة لبناء لاعبين متكاملين.",
    "hero.cta.register": "سجّل الآن",
    "hero.cta.dashboard": "الدخول للوحة التحكم",
    "hero.video.title": "جلسة تدريبية مباشرة",
    "hero.video.subtitle": "أكاديمية فيوتشر ستارز",
    
    // Stats
    "stats.players": "لاعب نشط",
    "stats.coaches": "مدرب محترف",
    "stats.satisfaction": "رضا أولياء الأمور",
    "stats.graduates": "لاعب محترف",
    
    // Features Section
    "features.title": "تطوير شامل للاعبين",
    "features.subtitle": "منهجنا المتكامل يشمل جميع جوانب تطوير اللاعب",
    "features.coaching.title": "تدريب متميز",
    "features.coaching.desc": "مدربون معتمدون من الاتحاد الأوروبي بخبرة احترافية",
    "features.analytics.title": "تحليل الأداء",
    "features.analytics.desc": "تحليلات متقدمة لمتابعة وتحسين مستوى اللاعبين",
    "features.mental.title": "الدعم النفسي",
    "features.mental.desc": "دعم نفسي رياضي لبناء الثقة والقوة الذهنية",
    "features.nutrition.title": "التغذية الرياضية",
    "features.nutrition.desc": "برامج غذائية مخصصة لتحقيق أفضل أداء رياضي",
    "features.video.title": "تحليل الفيديو",
    "features.video.desc": "تحليل مقاطع المباريات والتدريبات للتطوير التكتيكي",
    "features.tracking.title": "متابعة التقدم",
    "features.tracking.desc": "تقارير مفصلة عن تطور المهارات والنمو",
    
    // Gallery Section
    "gallery.title": "معرض التدريب",
    "gallery.subtitle": "شاهد لاعبينا أثناء التدريبات والمباريات",
    
    // Team Section
    "team.title": "فريق المدربين",
    "team.subtitle": "نخبة من المدربين المحترفين المتفانين في تطوير الجيل القادم",
    "team.viewAll": "عرض جميع المدربين",
    
    // Reviews Section
    "reviews.title": "آراء أولياء الأمور",
    "reviews.subtitle": "اسمع من العائلات التي عاشت تجربة فيوتشر ستارز",
    
    // FAQ Section
    "faq.title": "الأسئلة الشائعة",
    "faq.subtitle": "إجابات على أكثر الأسئلة شيوعاً حول الأكاديمية",
    
    // Location Section
    "location.title": "موقعنا",
    "location.subtitle": "زورونا في ذا سكوير كومباوند، القاهرة الجديدة",
    "location.address": "ذا سكوير كومباوند، التجمع الخامس، القاهرة الجديدة، مصر",
    
    // Footer
    "footer.description": "نُنمّي الجيل القادم من نجوم كرة القدم من خلال التدريب المتميز وعلوم الرياضة والتطوير الشامل.",
    "footer.quickLinks": "روابط سريعة",
    "footer.programs": "البرامج",
    "footer.contact": "تواصل معنا",
    "footer.rights": "جميع الحقوق محفوظة.",
    
    // Common
    "common.learnMore": "اعرف المزيد",
    "common.viewMore": "عرض المزيد",
    "common.backToHome": "العودة للرئيسية",
    "common.loading": "جاري التحميل...",
    "common.error": "حدث خطأ ما",
    "common.welcome": "أهلاً",
    
    // Pricing Page
    "pricing.title": "باقات الاشتراك",
    "pricing.subtitle": "اختر الباقة المناسبة لرحلة طفلك في كرة القدم",
    "pricing.monthly": "شهري",
    "pricing.quarterly": "٣ أشهر",
    "pricing.semiannual": "٦ أشهر",
    "pricing.annual": "سنوي",
    "pricing.perMonth": "/شهر",
    "pricing.save": "وفّر",
    "pricing.popular": "الأكثر شيوعاً",
    "pricing.bestValue": "أفضل قيمة",
    "pricing.includes": "تشمل الباقة",
    "pricing.excludes": "ملاحظة: الأسعار لا تشمل الزي الرياضي والفعاليات الخاصة",
    "pricing.getStarted": "ابدأ الآن",
    
    // Events Page
    "events.title": "الفعاليات القادمة",
    "events.subtitle": "انضم إلى تدريباتنا وبطولاتنا وفعالياتنا المميزة",
    "events.register": "سجّل",
    "events.spotsLeft": "مقاعد متبقية",
    "events.full": "مكتمل",
    
    // Contact Page
    "contact.title": "تواصل معنا",
    "contact.subtitle": "يسعدنا سماع رأيك",
    "contact.form.name": "الاسم",
    "contact.form.email": "البريد الإلكتروني",
    "contact.form.phone": "رقم الهاتف",
    "contact.form.message": "رسالتك",
    "contact.form.send": "إرسال",
    
    // Player Dashboard
    "player.profile": "ملف اللاعب",
    "player.skills": "المهارات",
    "player.activities": "الأنشطة",
    "player.targets": "الأهداف",
    "player.trends": "التطور",
    "player.explore": "استكشف",
    "player.attendance": "الحضور",
    "player.points": "النقاط",
    "player.rewards": "المكافآت",
    
    // Dashboard Menu
    "menu.videoAnalysis": "تحليل الفيديو",
    "menu.videoClipLibrary": "مكتبة مقاطع الفيديو",
    "menu.tacticalHub": "المركز التكتيكي",
    "menu.aiEmergencyMode": "وضع الطوارئ بالذكاء الاصطناعي",
    "menu.matchReports": "تقارير المباريات",
    "menu.opponentAnalysis": "تحليل الخصم",
    "menu.xgAnalytics": "تحليلات الأهداف المتوقعة",
    "menu.analytics": "التحليلات",
    "menu.gpsTracker": "تتبع GPS",
    "menu.matchManagement": "إدارة المباريات",
    "menu.recordMatchEvents": "تسجيل أحداث المباراة",
    "menu.leagueFixtures": "الدوري والمباريات",
    "menu.footballLaws": "قوانين كرة القدم",
    "menu.coachingCourses": "دورات التدريب",
    "menu.trainingVideos": "فيديوهات التدريب",
    "menu.coachAssessment": "تقييم المدرب",
    "menu.coachDashboard": "لوحة تحكم المدرب",
    
    // Attack Sequence Animator
    "attackSeq.title": "محاكي تسلسل الهجوم",
    "attackSeq.subtitle": "قم بإنشاء وتحليل تسلسلات الهجوم مع لاعبين متحركين",
    "attackSeq.formation": "التشكيلة",
    "attackSeq.selectFormation": "اختر التشكيلة",
    "attackSeq.playback": "التشغيل",
    "attackSeq.play": "تشغيل",
    "attackSeq.pause": "إيقاف مؤقت",
    "attackSeq.reset": "إعادة تعيين",
    "attackSeq.speed": "السرعة",
    "attackSeq.timeline": "الخط الزمني",
    "attackSeq.recording": "التسجيل",
    "attackSeq.startRecording": "بدء التسجيل",
    "attackSeq.stopRecording": "إيقاف التسجيل",
    "attackSeq.keyframes": "الإطارات الرئيسية",
    "attackSeq.dragPlayers": "اسحب اللاعبين لتغيير مواقعهم",
    "attackSeq.clickToRecord": "انقر على 'بدء التسجيل' لحفظ المواقع",
    "attackSeq.saveSequence": "حفظ التسلسل",
    "attackSeq.loadSequence": "تحميل التسلسل",
    "attackSeq.export": "تصدير",
    "attackSeq.patterns": "أنماط الهجوم",
    "attackSeq.counterAttack": "هجوم مرتد",
    "attackSeq.buildUp": "بناء اللعب",
    "attackSeq.wingAttack": "هجوم من الأطراف",
    "attackSeq.centralAttack": "هجوم مركزي",
    
    // Tactical Simulation
    "tactical.title": "المحاكاة التكتيكية",
    "tactical.subtitle": "خطط وحلل الاستراتيجيات التكتيكية",
    "tactical.homeTeam": "الفريق المضيف",
    "tactical.awayTeam": "الفريق الزائر",
    "tactical.formation": "التشكيلة",
    "tactical.strategy": "الاستراتيجية",
    "tactical.scenario": "السيناريو",
    "tactical.counterAttack": "هجوم مرتد",
    "tactical.highPress": "ضغط عالي",
    "tactical.wingAttack": "هجوم من الأطراف",
    "tactical.aiStrategies": "استراتيجيات الذكاء الاصطناعي",
    "tactical.recommended": "موصى به",
    "tactical.confidence": "الثقة",
    "tactical.apply": "تطبيق",
    "tactical.teamSetup": "إعداد الفريق",
    "tactical.opponentAnalysis": "تحليل الخصم",
    "tactical.loadAnalysis": "تحميل تحليل الخصم",
    "tactical.markingLines": "خطوط المراقبة",
    "tactical.offsideLine": "خط التسلل",
    "tactical.defensiveLine": "الخط الدفاعي",
    "tactical.animation": "الحركة",
    "tactical.play": "تشغيل",
    "tactical.pause": "إيقاف",
    "tactical.speed": "السرعة",
    "tactical.camera": "الكاميرا",
    "tactical.topView": "منظر علوي",
    "tactical.sideView": "منظر جانبي",
    "tactical.tacticalView": "منظر تكتيكي",
    "tactical.teamShape": "شكل الفريق",
    "tactical.width": "العرض",
    "tactical.compactness": "التماسك",
    "tactical.defensiveHeight": "ارتفاع الدفاع",
    "tactical.collisions": "التصادمات",
    "tactical.playerInstructions": "تعليمات اللاعبين",
    "tactical.phase": "المرحلة",
    "tactical.defense": "الدفاع",
    "tactical.transition": "الانتقال",
    "tactical.attack": "الهجوم",
    
    // 3D Match Review
    "matchReview.title": "مراجعة المباراة ثلاثية الأبعاد",
    "matchReview.subtitle": "راجع وحلل المباريات في بيئة ثلاثية الأبعاد",
    "matchReview.formation": "التشكيلة",
    "matchReview.camera": "الكاميرا",
    "matchReview.topView": "منظر علوي",
    "matchReview.sideView": "منظر جانبي",
    "matchReview.cornerView": "منظر الزاوية",
    "matchReview.drawingTools": "أدوات الرسم",
    "matchReview.move": "تحريك",
    "matchReview.arrow": "سهم",
    "matchReview.circle": "دائرة",
    "matchReview.zone": "منطقة",
    "matchReview.pencil": "قلم",
    "matchReview.clear": "مسح",
    "matchReview.save": "حفظ",
    "matchReview.playerMovement": "حركة اللاعبين",
    "matchReview.showTrails": "إظهار المسارات",
    "matchReview.trailLength": "طول المسار",
    "matchReview.playback": "التشغيل",
    "matchReview.play": "تشغيل",
    "matchReview.pause": "إيقاف",
    "matchReview.reset": "إعادة تعيين",
    "matchReview.speed": "السرعة",
    "matchReview.timeline": "الخط الزمني",
    "matchReview.events": "الأحداث",
    "matchReview.jumpToEvent": "الانتقال للحدث",
    "matchReview.playerInfo": "معلومات اللاعب",
    "matchReview.selectPlayer": "انقر على لاعب لعرض الإحصائيات",
    "matchReview.compare": "مقارنة",
    "matchReview.comparing": "مقارنة اللاعبين",
    "matchReview.distance": "المسافة",
    "matchReview.avgSpeed": "متوسط السرعة",
    "matchReview.touches": "اللمسات",
    "matchReview.passes": "التمريرات",
    "matchReview.tackles": "المراوغات",
    
    // Set Piece Planner
    "setPiece.title": "مخطط الكرات الثابتة",
    "setPiece.subtitle": "خطط وحلل الكرات الثابتة الهجومية والدفاعية",
    "setPiece.type": "نوع الكرة الثابتة",
    "setPiece.cornerKick": "ركلة ركنية",
    "setPiece.freeKick": "ركلة حرة",
    "setPiece.throwIn": "رمية تماس",
    "setPiece.penalty": "ركلة جزاء",
    "setPiece.goalKick": "ركلة مرمى",
    "setPiece.offensive": "هجومية",
    "setPiece.defensive": "دفاعية",
    "setPiece.templates": "القوالب الجاهزة",
    "setPiece.nearPost": "القائم القريب",
    "setPiece.farPost": "القائم البعيد",
    "setPiece.shortCorner": "ركنية قصيرة",
    "setPiece.directShot": "تسديدة مباشرة",
    "setPiece.wallSetup": "تشكيل الحائط",
    "setPiece.positioning": "تموضع اللاعبين",
    "setPiece.dragPlayers": "اسحب اللاعبين للتموضع",
    "setPiece.movements": "الحركات",
    "setPiece.addMovement": "إضافة حركة",
    "setPiece.drawArrow": "رسم سهم",
    "setPiece.drawZone": "رسم منطقة",
    "setPiece.timeline": "الخط الزمني",
    "setPiece.animate": "تحريك",
    "setPiece.play": "تشغيل",
    "setPiece.pause": "إيقاف",
    "setPiece.reset": "إعادة تعيين",
    "setPiece.save": "حفظ الخطة",
    "setPiece.load": "تحميل خطة",
    "setPiece.export": "تصدير",
    "setPiece.exportPDF": "تصدير PDF",
    "setPiece.exportImage": "تصدير صورة",
    "setPiece.myPlans": "خططي",
    "setPiece.teamLibrary": "مكتبة الفريق",
    
    // AI Tactical Planner
    "aiPlanner.title": "المخطط التكتيكي بالذكاء الاصطناعي",
    "aiPlanner.subtitle": "احصل على توصيات تكتيكية ذكية بناءً على تحليل الخصم",
    "aiPlanner.step1": "إعداد فريقك",
    "aiPlanner.step2": "تحليل الخصم",
    "aiPlanner.step3": "توصيات الذكاء الاصطناعي",
    "aiPlanner.step4": "المحاكاة",
    "aiPlanner.teamName": "اسم الفريق",
    "aiPlanner.formation": "التشكيلة",
    "aiPlanner.playStyle": "أسلوب اللعب",
    "aiPlanner.possession": "استحواذ",
    "aiPlanner.counterAttack": "هجوم مرتد",
    "aiPlanner.highPress": "ضغط عالي",
    "aiPlanner.defensive": "دفاعي",
    "aiPlanner.balanced": "متوازن",
    "aiPlanner.strengths": "نقاط القوة",
    "aiPlanner.keyPlayers": "اللاعبون الأساسيون",
    "aiPlanner.opponentName": "اسم الخصم",
    "aiPlanner.weaknesses": "نقاط الضعف",
    "aiPlanner.analyzing": "جاري التحليل...",
    "aiPlanner.generatePlan": "إنشاء خطة تكتيكية",
    "aiPlanner.tacticalOptions": "الخيارات التكتيكية",
    "aiPlanner.successRate": "معدل النجاح",
    "aiPlanner.pros": "الإيجابيات",
    "aiPlanner.cons": "السلبيات",
    "aiPlanner.selectTactic": "اختر هذه التكتيك",
    "aiPlanner.selected": "محدد",
    "aiPlanner.simulate": "محاكاة",
    "aiPlanner.savePlan": "حفظ الخطة",
    "aiPlanner.back": "رجوع",
    "aiPlanner.next": "التالي",
    
    // Tactical Hub
    "tacticalHub.title": "المركز التكتيكي",
    "tacticalHub.subtitle": "منصة شاملة للتخطيط والتحليل التكتيكي للمدربين",
    "tacticalHub.attackSequence": "تسلسل الهجوم",
    "tacticalHub.attackSequenceDesc": "خطط حركات الهجوم",
    "tacticalHub.tacticalSimulation": "المحاكاة التكتيكية",
    "tacticalHub.tacticalSimulationDesc": "اختبر التشكيلات والاستراتيجيات",
    "tacticalHub.matchReview": "مراجعة المباراة ثلاثية الأبعاد",
    "tacticalHub.matchReviewDesc": "حلل المباريات السابقة",
    "tacticalHub.setPieces": "الكرات الثابتة",
    "tacticalHub.setPiecesDesc": "ركنيات وخطط الكرات الحرة",
    "tacticalHub.aiPlanner": "المخطط التكتيكي بالذكاء الاصطناعي",
    "tacticalHub.aiPlannerDesc": "توصيات تكتيكية ذكية",
    "tacticalHub.loadOpponent": "تحميل تحليل الخصم",
    "tacticalHub.setPiecePlan": "خطة الكرة الثابتة",
    "tacticalHub.shortCornerPlay": "ركنية قصيرة",
    "tacticalHub.shortCornerDesc": "تمريرة قصيرة لإنشاء زاوية أفضل",
    "tacticalHub.typeCornerShort": "النوع: ركنية قصيرة",
    "tacticalHub.players": "اللاعبون",
    "tacticalHub.playAnimation": "تشغيل الحركة",
    "tacticalHub.savePlan": "حفظ الخطة",
    "tacticalHub.createCustom": "إنشاء مخصص",
    
    // Coach Certification Assessment
    "coachCert.title": "تقييم شهادة التدريب",
    "coachCert.subtitle": "اختبر معرفتك واحصل على رخص تدريب فيفا",
    "coachCert.grassroots": "شهادة التدريب الأساسية",
    "coachCert.grassrootsDesc": "تدريب على المستوى الأساسي لتطوير الشباب (الأعمار 4-12)",
    "coachCert.grassrootsBadge": "شهادة أساسية",
    "coachCert.uefaC": "رخصة يويفا/فيفا C",
    "coachCert.uefaCDesc": "المستوى الأساسي لتدريب الفرق الشبابية",
    "coachCert.uefaCBadge": "رخصة C",
    "coachCert.uefaB": "رخصة يويفا/فيفا B",
    "coachCert.uefaBDesc": "تدريب متقدم للمستويات شبه الاحترافية",
    "coachCert.uefaBBadge": "رخصة B",
    "coachCert.uefaA": "رخصة يويفا/فيفا A",
    "coachCert.uefaADesc": "مؤهل تدريب على المستوى الاحترافي",
    "coachCert.uefaABadge": "رخصة A",
    "coachCert.uefaPro": "رخصة يويفا برو / فيفا برو",
    "coachCert.uefaProDesc": "أعلى مؤهل تدريبي للأندية من الدرجة الأولى",
    "coachCert.uefaProBadge": "رخصة برو",
    "coachCert.duration": "المدة",
    "coachCert.questions": "الأسئلة",
    "coachCert.passingScore": "درجة النجاح",
    "coachCert.startAssessment": "بدء التقييم",
    "coachCert.minutes": "دقيقة",
    "coachCert.questionsCount": "سؤال",
    "coachCert.results": "النتائج",
    "coachCert.score": "النتيجة",
    "coachCert.passed": "نجحت!",
    "coachCert.failed": "لم تنجح",
    "coachCert.tryAgain": "حاول مرة أخرى",
    "coachCert.viewCertificate": "عرض الشهادة",
    "coachCert.congratulations": "تهانينا!",
    "coachCert.passedMessage": "لقد نجحت في التقييم",
    "coachCert.failedMessage": "لم تحقق درجة النجاح المطلوبة",
    "coachCert.yourScore": "نتيجتك",
    "coachCert.requiredScore": "الدرجة المطلوبة",
    "coachCert.pass": "نجاح",
    "coachCert.next": "التالي",
    "coachCert.previous": "السابق",
    "coachCert.submit": "إرسال الاختبار",
    "coachCert.backToCourses": "العودة إلى الدورات",
    "coachCert.question": "سؤال",
    "coachCert.of": "من",
    "coachCert.selectAnswer": "اختر إجابتك",
    "coachCert.progress": "التقدم",
    "coachCert.timeRemaining": "الوقت المتبقي",
    "coachCert.incompleteQuiz": "اختبار غير مكتمل",
    "coachCert.answerAllQuestions": "يرجى الإجابة على جميع الأسئلة قبل الإرسال.",
    "coachCert.quizSubmitted": "تم إرسال الاختبار بنجاح!",
    "coachCert.submissionError": "فشل إرسال الاختبار. يرجى المحاولة مرة أخرى.",
    "coachCert.correct": "صحيح",
    "coachCert.incorrect": "خطأ",
    "coachCert.total": "الإجمالي",
    "coachCert.certificateEarned": "تم الحصول على الشهادة!",
    "coachCert.congratsComplete": "تهانينا على إكمال الدورة!",
    "coachCert.tryAnotherCourse": "جرب دورة أخرى",
    "coachCert.answered": "مجاب",
    "coachCert.complete": "مكتمل",
    "coachCert.submitting": "جاري الإرسال...",
    
    // Training Sessions
    "training.title": "جلسات التدريب",
    "training.subtitle": "إدارة وجدولة جلسات التدريب لفرقك",
    "training.scheduleSession": "جدولة جلسة",
    "training.createSession": "جدولة جلسة تدريب",
    "training.createDescription": "إنشاء جلسة تدريب جديدة للفريق",
    "training.editSession": "تعديل جلسة التدريب",
    "training.sessionCreated": "تم إنشاء جلسة التدريب بنجاح",
    "training.sessionUpdated": "تم تحديث جلسة التدريب بنجاح",
    "training.sessionDeleted": "تم حذف جلسة التدريب",
    "training.sessionFailed": "فشل في إنشاء الجلسة",
    "training.confirmDelete": "هل أنت متأكد من حذف هذه الجلسة؟",
    "training.noSessions": "لا توجد جلسات تدريب مجدولة",
    "training.upcomingSessions": "الجلسات القادمة",
    "training.pastSessions": "الجلسات السابقة",
    "training.todaySessions": "جلسات اليوم",
    
    // Training Form Fields
    "training.sessionTitle": "عنوان الجلسة",
    "training.team": "الفريق",
    "training.selectTeam": "اختر الفريق",
    "training.date": "التاريخ",
    "training.startTime": "وقت البداية",
    "training.endTime": "وقت النهاية",
    "training.duration": "المدة",
    "training.location": "الموقع",
    "training.sessionType": "نوع الجلسة",
    "training.intensity": "الشدة",
    "training.objectives": "الأهداف",
    "training.drills": "التمارين",
    "training.description": "الوصف",
    "training.notes": "ملاحظات",
    "training.equipment": "المعدات المطلوبة",
    "training.attendance": "الحضور",
    "training.present": "حاضر",
    "training.absent": "غائب",
    "training.late": "متأخر",
    
    // Session Types
    "training.type.technical": "فني",
    "training.type.tactical": "تكتيكي",
    "training.type.physical": "بدني",
    "training.type.mental": "ذهني",
    "training.type.matchPrep": "إعداد المباراة",
    "training.type.recovery": "استشفاء",
    "training.type.mixed": "مختلط",
    
    // Intensity Levels
    "training.intensity.low": "منخفضة",
    "training.intensity.medium": "متوسطة",
    "training.intensity.high": "عالية",
    
    // Session Status
    "training.status.scheduled": "مجدولة",
    "training.status.inProgress": "جارية",
    "training.status.completed": "مكتملة",
    "training.status.cancelled": "ملغاة",
    
    // Actions
    "training.viewDetails": "عرض التفاصيل",
    "training.cancelSession": "إلغاء الجلسة",
    "training.markComplete": "وضع علامة مكتمل",
    "training.takeAttendance": "تسجيل الحضور",
    "training.addDrill": "إضافة تمرين",
    "training.saveDraft": "حفظ كمسودة",
    "training.publish": "نشر الجلسة",
    
    // Performance Tracking
    "performance.title": "تتبع الأداء",
    "performance.subtitle": "مراقبة وتحليل مقاييس أداء اللاعبين",
    "performance.overview": "نظرة عامة على الأداء",
    "performance.technicalScore": "النتيجة الفنية",
    "performance.physicalScore": "النتيجة البدنية",
    "performance.tacticalScore": "النتيجة التكتيكية",
    "performance.mentalScore": "النتيجة الذهنية",
    "performance.overallScore": "النتيجة الإجمالية",
    "performance.recentMetrics": "المقاييس الأخيرة",
    "performance.trends": "اتجاهات الأداء",
    "performance.comparison": "المقارنة مع الأقران",
    "performance.strengths": "نقاط القوة",
    "performance.weaknesses": "مجالات التحسين",
    "performance.recommendations": "التوصيات",
    
    // Physical Metrics
    "physical.title": "التدريب البدني",
    "physical.subtitle": "إدارة اللياقة البدنية والتمارين",
    "physical.distance": "المسافة المقطوعة",
    "physical.sprints": "العدو السريع",
    "physical.topSpeed": "السرعة القصوى",
    "physical.workload": "حمل التدريب",
    "physical.fatigue": "مستوى الإرهاق",
    "physical.recovery": "حالة التعافي",
    "physical.injury": "حالة الإصابة",
    "physical.workout": "خطة التمرين",
    "physical.strength": "تدريب القوة",
    "physical.endurance": "التحمل",
    "physical.speed": "تدريب السرعة",
    "physical.agility": "الرشاقة",
    "physical.flexibility": "المرونة",
    
    // Mental Coaching
    "mental.title": "التدريب الذهني",
    "mental.subtitle": "دعم التطور النفسي والمرونة",
    "mental.assessment": "التقييم الذهني",
    "mental.anxiety": "مستوى القلق",
    "mental.confidence": "الثقة",
    "mental.focus": "التركيز",
    "mental.resilience": "المرونة النفسية",
    "mental.stress": "مستوى التوتر",
    "mental.motivation": "الحافز",
    "mental.wellbeing": "الصحة العامة",
    "mental.session": "جلسة تدريب",
    "mental.techniques": "تقنيات ذهنية",
    "mental.progress": "تتبع التقدم",
    
    // Nutrition
    "nutrition.title": "التخطيط الغذائي",
    "nutrition.subtitle": "تحسين الأداء من خلال التغذية السليمة",
    "nutrition.mealPlan": "خطة الوجبات",
    "nutrition.calories": "السعرات الحرارية",
    "nutrition.protein": "البروتين",
    "nutrition.carbs": "الكربوهيدرات",
    "nutrition.fats": "الدهون",
    "nutrition.hydration": "الترطيب",
    "nutrition.supplements": "المكملات الغذائية",
    "nutrition.preTraining": "وجبة ما قبل التدريب",
    "nutrition.postTraining": "وجبة ما بعد التدريب",
    "nutrition.matchDay": "تغذية يوم المباراة",
    "nutrition.recommendations": "التوصيات الغذائية",
    
    // Events (additional keys)
    "events.upcoming": "الفعاليات القادمة",
    "events.past": "الفعاليات السابقة",
    "events.registered": "مسجل",
    "events.date": "تاريخ الفعالية",
    "events.location": "الموقع",
    "events.ageGroup": "الفئة العمرية",
    "events.capacity": "السعة",
    "events.cost": "التكلفة",
    "events.free": "مجاني",
    "events.details": "تفاصيل الفعالية",
    "events.registrationSuccess": "تم التسجيل في الفعالية بنجاح",
    "events.registrationFailed": "فشل التسجيل",
    
    // Match Management
    "match.title": "إدارة المباريات",
    "match.subtitle": "تتبع المباريات والنتائج وإحصائيات اللاعبين",
    "match.upcoming": "المباريات القادمة",
    "match.results": "نتائج المباريات",
    "match.schedule": "جدول المباريات",
    "match.opponent": "الخصم",
    "match.venue": "الملعب",
    "match.home": "على أرضنا",
    "match.away": "خارج الأرض",
    "match.kickoff": "وقت البداية",
    "match.result": "النتيجة",
    "match.score": "النتيجة",
    "match.win": "فوز",
    "match.loss": "خسارة",
    "match.draw": "تعادل",
    "match.goals": "الأهداف",
    "match.assists": "التمريرات الحاسمة",
    "match.lineup": "التشكيلة",
    "match.substitutions": "التبديلات",
    "match.statistics": "إحصائيات المباراة",
    "match.report": "تقرير المباراة",
    
    // Video Analysis
    "video.title": "تحليل الفيديو",
    "video.subtitle": "تحليل لقطات المباريات والتدريب",
    "video.upload": "رفع فيديو",
    "video.library": "مكتبة الفيديو",
    "video.recent": "الفيديوهات الأخيرة",
    "video.match": "فيديو المباراة",
    "video.training": "فيديو التدريب",
    "video.analysis": "التحليل",
    "video.tags": "العلامات",
    "video.notes": "ملاحظات",
    "video.share": "مشاركة",
    "video.download": "تحميل",
    
    // Analytics
    "analytics.title": "لوحة التحليلات",
    "analytics.subtitle": "رؤى مدفوعة بالبيانات وتحليل الأداء",
    "analytics.overview": "نظرة عامة",
    "analytics.team": "تحليلات الفريق",
    "analytics.player": "تحليلات اللاعب",
    "analytics.comparison": "المقارنة",
    "analytics.trends": "الاتجاهات",
    "analytics.reports": "التقارير",
    "analytics.export": "تصدير البيانات",
    
    // GPS Tracker
    "gps.title": "تتبع GPS",
    "gps.subtitle": "مراقبة حركة اللاعبين وحمل العمل",
    "gps.distance": "المسافة",
    "gps.speed": "السرعة",
    "gps.acceleration": "التسارع",
    "gps.heartRate": "معدل ضربات القلب",
    "gps.zones": "مناطق الشدة",
    "gps.heatmap": "خريطة الحركة الحرارية",
    "gps.session": "بيانات الجلسة",
    "gps.sync": "مزامنة البيانات",
    
    // Live Match Mode
    "liveMatchMode": "وضع المباراة الحية",
    "liveMatchModeDescription": "تتبع وإدارة مباراتك في الوقت الفعلي مع مساعدة الذكاء الاصطناعي التكتيكي",
    "startNewMatch": "بدء مباراة جديدة",
    "matchStarted": "بدأت المباراة",
    "liveMatchModeActivated": "تم تفعيل وضع المباراة الحية بنجاح",
    "selectTeam": "اختر الفريق",
    "opponent": "الخصم",
    "opponentName": "اسم الفريق الخصم",
    "venue": "الملعب",
    "home": "على أرضنا",
    "away": "خارج الأرض",
    "ourFormation": "تشكيلتنا",
    "opponentFormation": "تشكيلة الخصم",
    "optional": "اختياري",
    "selectFormation": "اختر التشكيلة",
    "starting": "جاري البدء...",
    "startMatch": "بدء المباراة",
    "matchTime": "وقت المباراة",
    "start": "بدء",
    "pause": "إيقاف مؤقت",
    "resume": "استئناف",
    "finish": "إنهاء",
    "score": "النتيجة",
    "us": "نحن",
    "formation": "التشكيلة",
    "changeTactics": "تغيير التكتيك",
    "quickActions": "إجراءات سريعة",
    "goal": "هدف",
    "yellowCard": "بطاقة صفراء",
    "redCard": "بطاقة حمراء",
    "substitution": "تبديل",
    "injury": "إصابة",
    "penalty": "ركلة جزاء",
    "substitutionsUsed": "التبديلات المستخدمة",
    "yellowCards": "البطاقات الصفراء",
    "redCards": "البطاقات الحمراء",
    "liveStatistics": "الإحصائيات المباشرة",
    "possession": "الاستحواذ",
    "shots": "التسديدات",
    "onTarget": "على المرمى",
    "opponentShots": "تسديدات الخصم",
    "corners": "الركنيات",
    "fouls": "الأخطاء",
    "aiTacticalAssistant": "المساعد التكتيكي بالذكاء الاصطناعي",
    "analyzing": "جاري التحليل...",
    "getAIAdvice": "احصل على نصيحة الذكاء الاصطناعي",
    "clickToGetAIAdvice": "اضغط على الزر أعلاه للحصول على توصيات تكتيكية من الذكاء الاصطناعي",
    "matchEvents": "أحداث المباراة",
    "assist": "تمريرة حاسمة",
    "noEventsYet": "لم يتم تسجيل أي أحداث بعد",
    "tacticalChanges": "التغييرات التكتيكية",
    "recordEvent": "تسجيل حدث",
    "eventType": "نوع الحدث",
    "team": "الفريق",
    "playerName": "اسم اللاعب",
    "enterPlayerName": "أدخل اسم اللاعب",
    "assistBy": "تمريرة حاسمة من",
    "enterAssistPlayerName": "أدخل اسم صاحب التمريرة الحاسمة",
    "playerOut": "اللاعب الخارج",
    "notes": "ملاحظات",
    "additionalNotes": "ملاحظات إضافية",
    "recording": "جاري التسجيل...",
    "eventRecorded": "تم تسجيل الحدث",
    "matchEventSaved": "تم حفظ حدث المباراة بنجاح",
    "changeType": "نوع التغيير",
    "tacticalInstruction": "تعليمات تكتيكية",
    "playerRole": "دور اللاعب",
    "pressingIntensity": "شدة الضغط",
    "defensiveLine": "الخط الدفاعي",
    "newFormation": "التشكيلة الجديدة",
    "newValue": "القيمة الجديدة",
    "enterNewValue": "أدخل القيمة الجديدة",
    "reason": "السبب",
    "whyThisChange": "لماذا هذا التغيير؟",
    "saving": "جاري الحفظ...",
    "saveTacticalChange": "حفظ التغيير التكتيكي",
    "tacticsChanged": "تم تغيير التكتيك",
    "tacticalChangeSaved": "تم حفظ التغيير التكتيكي بنجاح",
    "matchFinished": "انتهت المباراة",
    "matchDataSaved": "تم حفظ بيانات المباراة بنجاح",
    "confirmFinishMatch": "هل أنت متأكد من إنهاء هذه المباراة؟",
    "fillAllFields": "يرجى ملء جميع الحقول المطلوبة",
    "ownGoal": "هدف في مرماه",
    "varDecision": "قرار VAR",
    "loading": "جاري التحميل...",
    "error": "خطأ",
    
    // Heatmap & GPS
    "playerHeatmap": "الخريطة الحرارية للاعب",
    "refresh": "تحديث",
    "download": "تحميل",
    "selectPlayer": "اختر لاعب",
    "showAllPlayers": "إظهار جميع اللاعبين",
    "selectPlayerToViewHeatmap": "اختر لاعباً لعرض خريطته الحرارية",
    "lowToHighIntensity": "من الشدة المنخفضة إلى العالية",
    "autoRefreshEvery30Seconds": "تحديث تلقائي كل 30 ثانية",
    "gpsIntegration": "تكامل GPS",
    "gpsIntegrationDescription": "استيراد بيانات تتبع GPS أو مزامنة مباشرة أثناء المباراة",
    "liveGpsSync": "مزامنة GPS المباشرة",
    "deviceId": "معرف الجهاز",
    "startGpsSync": "بدء مزامنة GPS",
    "activeSyncs": "المزامنات النشطة",
    "dataPoints": "نقاط بيانات",
    "importGpsFile": "استيراد ملف GPS",
    "importGpsFileDescription": "رفع ملف CSV يحتوي على بيانات تتبع GPS",
    "importing": "جاري الاستيراد...",
    "clickToUploadCsv": "اضغط لرفع ملف CSV",
    "dataPointsImported": "تم استيراد نقاط البيانات بنجاح",
    "importFailed": "فشل الاستيراد",
    "instructions": "التعليمات",
    "gpsInstruction1": "ابدأ المزامنة المباشرة لتتبع مواقع اللاعبين في الوقت الفعلي أثناء المباراة",
    "gpsInstruction2": "أو قم باستيراد ملف CSV يحتوي على بيانات GPS التاريخية (التنسيق: playerId, minute, x, y, speed, heartRate)",
    "gpsInstruction3": "سيتم تحديث الخريطة الحرارية تلقائياً كل 30 ثانية أثناء المباريات الحية",
    "gpsSyncStarted": "بدأت مزامنة GPS",
    "gpsSyncStartedSuccess": "تم بدء مزامنة GPS بنجاح للاعب المحدد",
    "failedToStartGpsSync": "فشل بدء مزامنة GPS",
    "gpsDataImported": "تم استيراد بيانات GPS",
    "failedToImportGpsData": "فشل استيراد بيانات GPS",
    "gpsSync": "مزامنة GPS",
    
    // AI Tools Module
    "aiTools.title": "أدوات الذكاء الاصطناعي",
    "aiTools.subtitle": "أدوات متقدمة مدعومة بالذكاء الاصطناعي لتحليل وتطوير الأداء",
    "aiCoach.title": "مساعد المدرب بالذكاء الاصطناعي",
    "aiCoach.subtitle": "احصل على نصائح تكتيكية وتدريبية مخصصة من الذكاء الاصطناعي",
    "aiCoach.askQuestion": "اسأل سؤالاً",
    "aiCoach.placeholder": "اكتب سؤالك هنا...",
    "aiCoach.send": "إرسال",
    "aiCoach.thinking": "جاري التفكير...",
    "aiCoach.suggestions": "اقتراحات",
    "aiCoach.history": "المحادثات السابقة",
    "aiCoach.newChat": "محادثة جديدة",
    "aiCoach.clearHistory": "مسح المحادثات",
    
    "aiMatchCoach.title": "مدرب المباراة بالذكاء الاصطناعي",
    "aiMatchCoach.subtitle": "تحليل تكتيكي في الوقت الفعلي أثناء المباريات",
    "aiMatchCoach.liveAnalysis": "تحليل مباشر",
    "aiMatchCoach.tacticalAdvice": "نصيحة تكتيكية",
    "aiMatchCoach.substitutionSuggestion": "اقتراح تبديل",
    "aiMatchCoach.formationChange": "تغيير التشكيلة",
    
    "aiEmergency.title": "وضع الطوارئ بالذكاء الاصطناعي",
    "aiEmergency.subtitle": "حلول تكتيكية سريعة للمواقف الحرجة في المباراة",
    "aiEmergency.situation": "الموقف الحالي",
    "aiEmergency.losingLate": "متأخرون في الدقائق الأخيرة",
    "aiEmergency.redCard": "بطاقة حمراء",
    "aiEmergency.injuryKey": "إصابة لاعب أساسي",
    "aiEmergency.penaltyAgainst": "ركلة جزاء ضدنا",
    "aiEmergency.getSolution": "احصل على الحل",
    
    "aiPrediction.title": "توقع الأداء",
    "aiPrediction.subtitle": "تنبؤات مدعومة بالذكاء الاصطناعي لأداء اللاعبين",
    "aiPrediction.playerPotential": "إمكانيات اللاعب",
    "aiPrediction.injuryRisk": "خطر الإصابة",
    "aiPrediction.formPrediction": "توقع المستوى",
    
    "aiFormation.title": "محاكاة التشكيلة بالذكاء الاصطناعي",
    "aiFormation.subtitle": "اختبر التشكيلات المختلفة واحصل على توصيات الذكاء الاصطناعي",
    "aiFormation.simulate": "محاكاة",
    "aiFormation.recommendation": "التوصية",
    "aiFormation.strengths": "نقاط القوة",
    "aiFormation.weaknesses": "نقاط الضعف",
    
    "aiCalendar.title": "التقويم الذكي",
    "aiCalendar.subtitle": "جدولة ذكية للتدريبات والمباريات",
    "aiCalendar.optimize": "تحسين الجدول",
    "aiCalendar.suggestions": "اقتراحات",
    
    "aiVideo.title": "تحليل الفيديو بالذكاء الاصطناعي",
    "aiVideo.subtitle": "تحليل آلي للقطات المباريات والتدريب",
    "aiVideo.analyze": "تحليل",
    "aiVideo.keyMoments": "اللحظات الرئيسية",
    "aiVideo.playerTracking": "تتبع اللاعبين",
    "aiVideo.tacticalInsights": "رؤى تكتيكية",
    
    "aiReport.title": "مولد التقارير بالذكاء الاصطناعي",
    "aiReport.subtitle": "إنشاء تقارير مباريات مفصلة تلقائياً",
    "aiReport.generate": "إنشاء تقرير",
    "aiReport.matchSummary": "ملخص المباراة",
    "aiReport.playerRatings": "تقييمات اللاعبين",
    "aiReport.tacticalAnalysis": "التحليل التكتيكي",
    
    // Modules Navigation
    "module.dashboard": "لوحة التحكم",
    "module.players": "إدارة اللاعبين",
    "module.training": "التدريب",
    "module.matches": "المباريات والتكتيكات",
    "module.video": "تحليل الفيديو",
    "module.ai": "أدوات الذكاء الاصطناعي",
    "module.analytics": "التحليلات والتقارير",
    "module.staff": "أدوات الطاقم",
    "module.education": "التعليم",
    "module.community": "المجتمع",
    "module.admin": "الإدارة",
    
    // Common Actions
    "action.save": "حفظ",
    "action.cancel": "إلغاء",
    "action.delete": "حذف",
    "action.edit": "تعديل",
    "action.add": "إضافة",
    "action.search": "بحث",
    "action.filter": "تصفية",
    "action.export": "تصدير",
    "action.import": "استيراد",
    "action.refresh": "تحديث",
    "action.back": "رجوع",
    "action.next": "التالي",
    "action.previous": "السابق",
    "action.submit": "إرسال",
    "action.confirm": "تأكيد",
    "action.close": "إغلاق",
    
    // Status Messages
    "status.loading": "جاري التحميل...",
    "status.saving": "جاري الحفظ...",
    "status.success": "تمت العملية بنجاح",
    "status.error": "حدث خطأ",
    "status.noData": "لا توجد بيانات",
    "status.noResults": "لا توجد نتائج",
    
    // User Roles
    "role.admin": "مدير",
    "role.coach": "مدرب",
    "role.player": "لاعب",
    "role.parent": "ولي أمر",
    "role.nutritionist": "أخصائي تغذية",
    "role.mentalCoach": "مدرب نفسي",
    "role.physicalTrainer": "مدرب لياقة",
    
    // AI Dashboard
    "aiDashboard.title": "لوحة الذكاء الاصطناعي",
    "aiDashboard.subtitle": "مركز شامل لجميع أدوات التدريب المدعومة بالذكاء الاصطناعي",
    "aiDashboard.quickStats": "إحصائيات سريعة",
    "aiDashboard.aiTools": "أدوات الذكاء الاصطناعي",
    "aiDashboard.recommendations": "توصيات الذكاء الاصطناعي",
    "aiDashboard.smartSuggestions": "اقتراحات ذكية بناءً على بيانات فريقك",
    "aiDashboard.needHelp": "هل تحتاج مساعدة سريعة من الذكاء الاصطناعي؟",
    "aiDashboard.askAI": "اسأل مساعد المدرب الذكي",
    "aiDashboard.teamTrend": "اتجاه أداء الفريق",
    "aiDashboard.improving": "تحسن",
    "aiDashboard.analysesThisWeek": "تحليلات هذا الأسبوع",
    "aiDashboard.trainingPlans": "خطط التدريب المُنشأة",
    "aiDashboard.matchReports": "تقارير المباريات المُنشأة",
    "aiDashboard.thisWeek": "هذا الأسبوع",
    
    // AI Dashboard Tools
    "aiDashboard.playerAnalysis": "تحليل اللاعبين",
    "aiDashboard.playerAnalysisDesc": "تحليل أداء اللاعبين بالذكاء الاصطناعي مع نقاط القوة والضعف والتوصيات",
    "aiDashboard.viewPlayers": "عرض اللاعبين",
    "aiDashboard.matchReportGen": "مولد تقارير المباريات",
    "aiDashboard.matchReportGenDesc": "إنشاء تقارير شاملة للمباريات مع اللحظات الرئيسية وتقييمات اللاعبين",
    "aiDashboard.generateReport": "إنشاء تقرير",
    "aiDashboard.trainingPlanner": "مخطط جلسات التدريب",
    "aiDashboard.trainingPlannerDesc": "إنشاء خطط تدريب مخصصة بناءً على نقاط ضعف الفريق وبيانات الأداء",
    "aiDashboard.planTraining": "تخطيط التدريب",
    "aiDashboard.aiCalendar": "التقويم الذكي",
    "aiDashboard.aiCalendarDesc": "اقتراحات جدولة ذكية بناءً على أنماط الأداء ومواعيد المباريات",
    "aiDashboard.viewCalendar": "عرض التقويم",
    "aiDashboard.playerComparison": "مقارنة اللاعبين",
    "aiDashboard.playerComparisonDesc": "مقارنة عدة لاعبين جنباً إلى جنب مع رؤى الذكاء الاصطناعي واقتراحات التشكيلة",
    "aiDashboard.comparePlayers": "مقارنة اللاعبين",
    "aiDashboard.tacticalHub": "المركز التكتيكي",
    "aiDashboard.tacticalHubDesc": "تحليل تكتيكي متقدم مع التشكيلات والخرائط الحرارية واقتراحات الذكاء الاصطناعي",
    "aiDashboard.openHub": "فتح المركز",
    "aiDashboard.aiCoach": "مساعد المدرب الذكي",
    "aiDashboard.aiCoachDesc": "اسأل أي سؤال تدريبي واحصل على نصائح خبيرة مع بيانات الفريق واللاعبين",
    "aiDashboard.askAICoach": "اسأل الذكاء الاصطناعي",
    "aiDashboard.aiVideoAnalysis": "تحليل الفيديو بالذكاء الاصطناعي",
    "aiDashboard.aiVideoAnalysisDesc": "تحليل فيديوهات المباريات بالذكاء الاصطناعي لاكتشاف التشكيلات والأنماط التكتيكية",
    "aiDashboard.analyzeVideo": "تحليل الفيديو",
    "aiDashboard.performancePrediction": "توقع الأداء",
    "aiDashboard.performancePredictionDesc": "توقعات مدعومة بالذكاء الاصطناعي لأداء اللاعبين والفريق في المباريات القادمة",
    "aiDashboard.viewPredictions": "عرض التوقعات",
    "aiDashboard.emergencyMode": "وضع الطوارئ التكتيكي",
    "aiDashboard.emergencyModeDesc": "نصائح تكتيكية فورية للمواقف الحرجة في المباراة مع تعديلات التشكيلة",
    
    // AI Dashboard Recommendations
    "aiDashboard.analyzeTopPerformers": "تحليل أفضل اللاعبين",
    "aiDashboard.topPerformersDesc": "3 لاعبين أظهروا تحسناً ملحوظاً هذا الأسبوع. قم بتحليل الذكاء الاصطناعي لفهم تقدمهم.",
    "aiDashboard.scheduleTraining": "جدولة جلسة تدريب",
    "aiDashboard.scheduleTrainingDesc": "درجات اللياقة البدنية للفريق أقل من المتوسط. أنشئ خطة تدريب تركز على التكييف.",
    "aiDashboard.generateMatchReport": "إنشاء تقرير المباراة",
    "aiDashboard.generateMatchReportDesc": "بيانات آخر مباراة متاحة. أنشئ تقريراً شاملاً مدعوماً بالذكاء الاصطناعي مع رؤى.",
    "aiDashboard.compareKeyPlayers": "مقارنة اللاعبين الأساسيين",
    "aiDashboard.compareKeyPlayersDesc": "عدة لاعبين يتنافسون على نفس المركز. استخدم مقارنة الذكاء الاصطناعي للعثور على الأنسب.",
    "aiDashboard.compareNow": "قارن الآن",
    
    // xG Analytics
    "xg.title": "لوحة تحليلات الأهداف المتوقعة",
    "xg.subtitle": "تحليل متقدم للتسديدات والأهداف المتوقعة",
    "xg.matchAnalysis": "تحليل المباراة",
    "xg.shotMap": "خريطة التسديدات",
    "xg.passMap": "خريطة التمريرات",
    "xg.defensiveMap": "خريطة الدفاع",
    "xg.teamStats": "إحصائيات الفريق",
    "xg.playerStats": "إحصائيات اللاعبين",
    "xg.expectedGoals": "الأهداف المتوقعة",
    "xg.actualGoals": "الأهداف الفعلية",
    "xg.shots": "التسديدات",
    "xg.shotsOnTarget": "تسديدات على المرمى",
    "xg.passAccuracy": "دقة التمريرات",
    "xg.possession": "الاستحواذ",
    "xg.keyPasses": "التمريرات الحاسمة",
    "xg.touches": "اللمسات",
    "xg.selectTeam": "اختر الفريق",
    "xg.homeTeam": "الفريق المضيف",
    "xg.awayTeam": "الفريق الضيف",
    "xg.goal": "هدف",
    "xg.miss": "فشل",
    "xg.minute": "الدقيقة",
    "xg.overperforming": "أداء أعلى من المتوقع",
    "xg.underperforming": "أداء أقل من المتوقع",
    "xg.exportData": "تصدير البيانات",
    "xg.filterByTeam": "تصفية حسب الفريق",
    
    // Formation Builder
    "formation.title": "منشئ التشكيلات",
    "formation.subtitle": "أنشئ وخصص تشكيلات الفريق بالسحب والإفلات",
    "formation.selectFormation": "اختر التشكيلة",
    "formation.dragPlayers": "اسحب اللاعبين لتغيير مواقعهم",
    "formation.saveFormation": "حفظ التشكيلة",
    "formation.loadFormation": "تحميل تشكيلة",
    "formation.resetFormation": "إعادة تعيين",
    "formation.playerRoles": "أدوار اللاعبين",
    "formation.tactics": "التكتيكات",
    "formation.defensive": "دفاعي",
    "formation.balanced": "متوازن",
    "formation.attacking": "هجومي",
    
    // Set Piece Designer
    "setPieceDesigner.title": "مصمم الكرات الثابتة",
    "setPieceDesigner.subtitle": "صمم وخطط للركنيات والركلات الحرة",
    "setPieceDesigner.cornerKick": "ركلة ركنية",
    "setPieceDesigner.freeKick": "ركلة حرة",
    "setPieceDesigner.throwIn": "رمية تماس",
    "setPieceDesigner.penalty": "ركلة جزاء",
    "setPieceDesigner.offensive": "هجومية",
    "setPieceDesigner.defensive": "دفاعية",
    "setPieceDesigner.saveDesign": "حفظ التصميم",
    "setPieceDesigner.loadDesign": "تحميل تصميم",
    "setPieceDesigner.animate": "تشغيل الحركة",
    
    // Live Match Notes
    "liveNotes.title": "ملاحظات المباراة الحية",
    "liveNotes.subtitle": "سجل ملاحظاتك أثناء المباراة في الوقت الفعلي",
    "liveNotes.addNote": "إضافة ملاحظة",
    "liveNotes.minute": "الدقيقة",
    "liveNotes.category": "الفئة",
    "liveNotes.tactical": "تكتيكي",
    "liveNotes.technical": "فني",
    "liveNotes.physical": "بدني",
    "liveNotes.mental": "ذهني",
    "liveNotes.exportNotes": "تصدير الملاحظات",
    
    // Match Event Recording
    "matchEvent.title": "تسجيل أحداث المباراة",
    "matchEvent.subtitle": "سجل الأهداف والبطاقات والتبديلات والأحداث الأخرى",
    "matchEvent.recordGoal": "تسجيل هدف",
    "matchEvent.recordCard": "تسجيل بطاقة",
    "matchEvent.recordSubstitution": "تسجيل تبديل",
    "matchEvent.recordInjury": "تسجيل إصابة",
    "matchEvent.eventTimeline": "الجدول الزمني للأحداث",
    
    // Video Clip Library
    "videoClip.title": "مكتبة مقاطع الفيديو",
    "videoClip.subtitle": "تصفح وإدارة مقاطع الفيديو التدريبية والمباريات",
    "videoClip.createClip": "إنشاء مقطع",
    "videoClip.editClip": "تعديل المقطع",
    "videoClip.deleteClip": "حذف المقطع",
    "videoClip.shareClip": "مشاركة المقطع",
    "videoClip.tags": "العلامات",
    "videoClip.duration": "المدة",
    "videoClip.source": "المصدر",
    
    // Create Video Clip
    "createClip.title": "إنشاء مقطع فيديو",
    "createClip.subtitle": "قص وإنشاء مقاطع من الفيديوهات الكاملة",
    "createClip.selectVideo": "اختر الفيديو",
    "createClip.startTime": "وقت البداية",
    "createClip.endTime": "وقت النهاية",
    "createClip.clipName": "اسم المقطع",
    "createClip.description": "الوصف",
    "createClip.createClip": "إنشاء المقطع",
    
    // Skill Assessment
    "skillAssess.title": "تقييم المهارات",
    "skillAssess.subtitle": "تقييم شامل لمهارات اللاعبين",
    "skillAssess.technical": "المهارات الفنية",
    "skillAssess.tactical": "المهارات التكتيكية",
    "skillAssess.physical": "المهارات البدنية",
    "skillAssess.mental": "المهارات الذهنية",
    "skillAssess.overall": "التقييم الإجمالي",
    "skillAssess.saveAssessment": "حفظ التقييم",
    "skillAssess.history": "تاريخ التقييمات",
    
    // Session Comparison
    "sessionComp.title": "مقارنة الجلسات",
    "sessionComp.subtitle": "قارن أداء جلسات التدريب المختلفة",
    "sessionComp.selectSessions": "اختر الجلسات للمقارنة",
    "sessionComp.metrics": "المقاييس",
    "sessionComp.intensity": "الشدة",
    "sessionComp.duration": "المدة",
    "sessionComp.attendance": "الحضور",
    
    // 3D Match Review
    "matchReview3d.title": "مراجعة المباراة ثلاثية الأبعاد",
    "matchReview3d.subtitle": "راجع وحلل المباريات في بيئة ثلاثية الأبعاد تفاعلية",
    "matchReview3d.selectMatch": "اختر المباراة",
    "matchReview3d.playback": "التشغيل",
    "matchReview3d.cameraAngle": "زاوية الكاميرا",
    "matchReview3d.topView": "منظر علوي",
    "matchReview3d.sideView": "منظر جانبي",
    "matchReview3d.playerView": "منظر اللاعب",
    "matchReview3d.drawingTools": "أدوات الرسم",
    
    // Injury Tracking
    "injuryTrack.title": "تتبع الإصابات",
    "injuryTrack.subtitle": "إدارة ومتابعة إصابات اللاعبين وبرامج التعافي",
    "injuryTrack.currentInjuries": "الإصابات الحالية",
    "injuryTrack.recoveryProgress": "تقدم التعافي",
    "injuryTrack.injuryHistory": "تاريخ الإصابات",
    "injuryTrack.addInjury": "إضافة إصابة",
    "injuryTrack.injuryType": "نوع الإصابة",
    "injuryTrack.severity": "الشدة",
    "injuryTrack.expectedReturn": "تاريخ العودة المتوقع",
    "injuryTrack.treatment": "العلاج",
    "injuryTrack.mild": "خفيفة",
    "injuryTrack.moderate": "متوسطة",
    "injuryTrack.severe": "شديدة",
    
    // Admin Pages
    "admin.homeContent": "محتوى الصفحة الرئيسية",
    "admin.homeContentDesc": "إدارة محتوى الصفحة الرئيسية للموقع",
    "admin.roleManagement": "إدارة الأدوار",
    "admin.roleManagementDesc": "إدارة أدوار وصلاحيات المستخدمين",
    "admin.cacheManagement": "إدارة الذاكرة المؤقتة",
    "admin.cacheManagementDesc": "مسح وإدارة ذاكرة التخزين المؤقت للنظام",
    "admin.clearCache": "مسح الذاكرة المؤقتة",
    "admin.cacheCleared": "تم مسح الذاكرة المؤقتة بنجاح",
    "admin.editContent": "تعديل المحتوى",
    "admin.saveContent": "حفظ المحتوى",
    "admin.preview": "معاينة",
    
    // Pass Network Viewer
    "passNetwork.title": "عارض شبكة التمريرات",
    "passNetwork.subtitle": "تحليل أنماط التمرير والاتصالات بين اللاعبين",
    "passNetwork.selectMatch": "اختر المباراة",
    "passNetwork.passCount": "عدد التمريرات",
    "passNetwork.passAccuracy": "دقة التمريرات",
    "passNetwork.keyConnections": "الاتصالات الرئيسية",
    "passNetwork.mostActive": "الأكثر نشاطاً",
    "passNetwork.leastActive": "الأقل نشاطاً",
    
    // Data Analysis Pro
    "dataAnalysis.title": "تحليل البيانات المتقدم",
    "dataAnalysis.subtitle": "تحليل متعمق لبيانات الأداء والإحصائيات",
    "dataAnalysis.selectMetrics": "اختر المقاييس",
    "dataAnalysis.timeRange": "النطاق الزمني",
    "dataAnalysis.compareWith": "مقارنة مع",
    "dataAnalysis.exportReport": "تصدير التقرير",
    "dataAnalysis.trends": "الاتجاهات",
    "dataAnalysis.insights": "الرؤى",
    
    // Heatmap Professional
    "heatmap.title": "الخريطة الحرارية الاحترافية",
    "heatmap.subtitle": "تحليل مواقع وتحركات اللاعبين على الملعب",
    "heatmap.selectPlayer": "اختر اللاعب",
    "heatmap.selectMatch": "اختر المباراة",
    "heatmap.intensity": "الشدة",
    "heatmap.zones": "المناطق",
    "heatmap.attackingThird": "الثلث الهجومي",
    "heatmap.middleThird": "الثلث الأوسط",
    "heatmap.defensiveThird": "الثلث الدفاعي",
    "heatmap.leftSide": "الجانب الأيسر",
    "heatmap.rightSide": "الجانب الأيمن",
    "heatmap.center": "الوسط",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check if user has manually selected a language before
    const saved = localStorage.getItem("language");
    if (saved) {
      return saved as Language;
    }
    
    // Auto-detect browser language
    const browserLang = navigator.language || (navigator as any).userLanguage;
    // Check if browser language is Arabic
    if (browserLang.startsWith('ar')) {
      return "ar";
    }
    
    // Default to English
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    const newLang = language === "en" ? "ar" : "en";
    setLanguage(newLang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

